jjuuliak/G15-SLT-STEER-2

- frontend/eslint.config.mjs
- frontend/package-lock.json
- frontend/package.json
> Fix vulnerabilities and add ESLint

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/LogIn.jsx
- frontend/src/routes/AppRoutes.jsx
Login UI for /login route without validation logic or navigation to register or forgot password
> Create initial login page

- frontend/src/pages/LogIn.jsx
- frontend/src/pages/Register.jsx
- frontend/src/routes/AppRoutes.jsx
> Create first version of user registration

- backend/LLMService.py
Added a method to LLMService that corrects spelling, grammatical, and punctuation errors in the user given prompt so that RAG results won't be affected by them.
Made the model an instance variable to avoid creating it every time during function calls. This model is then called to generate content when fixing a prompt.
> Add method for correcting any mistakes in the user prompt

- backend/main.py
- frontend/src/components/Chat.jsx
- frontend/src/components/Message.jsx
- frontend/src/pages/Home/Home.js
First version of chatbot UI component that calls backend for now as a test user, backend cors allows all origins
> Add first version of chatbot ui

- backend/models/login_model.py
- backend/models/medical_info_model.py
- backend/models/user_model.py
Renamed models to comply with general conventions. Split the user model into two models: one holding general data, one holding login data. Added a new model for medical info, only containing the very base information.
> Refactor user model, add model for medical info

- backend/auth_service.py
Added an auth service class whose pupose is to provide authentication/authorization functions. Only functions for hashing and checking passwords using bcrypt are currently implemented.
> Initialize auth service

- frontend/package-lock.json
- frontend/package.json
- frontend/public/locales/en/translation.json
- frontend/public/locales/fi/translation.json
- frontend/src/i18n.js
- frontend/src/index.js
- frontend/src/pages/Register.jsx
> Add translations to the app

- frontend/public/locales/en/translation.json
- frontend/public/locales/fi/translation.json
- frontend/src/components/LifelineImage.jsx
- frontend/src/components/Logo.jsx
- frontend/src/pages/LogIn.jsx
- frontend/src/pages/Register.jsx
- frontend/src/services/authService.js
> Modify the register view

- frontend/src/components/Chat.jsx
- frontend/src/components/Message.jsx
- frontend/src/pages/LogIn.jsx
- frontend/src/pages/Register.jsx
- frontend/src/pages/home/Home.js
- frontend/src/redux/reducers/authReducer.js
- frontend/src/routes/AppRoutes.jsx
- frontend/src/theme/theme.js
Connect chat to the back end and modify the view to look more like the design.
Closes #113
> Chat view changes

- backend/routes/login.py
- frontend/public/locales/en/translation.json
- frontend/public/locales/fi/translation.json
- frontend/src/pages/LogIn.jsx
- frontend/src/services/authService.js
Divided for now into invalid login credentials and "all other errors"
> Add error message for login

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Chat.jsx
- frontend/src/components/Message.jsx
> Show markdown messages correctly

- backend/LLMService.py
- backend/main.py
- backend/message_attributes.py
- backend/models/medical_info_model.py
- backend/routes/login.py
- backend/routes/user.py
https://github.com/jjuuliak/G15-SLT-STEER-2/issues/146
> Implement new attributes + remove user_data from login/register, fix register

- frontend/package-lock.json
- frontend/package.json
- frontend/src/__tests__/authService.test.js
tests for handleLogin and RegisterUser services
successful login, 2x failed login, successful registration, failed registration (existing user)
> Add first tests to authservice

- backend/LLMService.py
- backend/chat_history.py
- backend/message_attributes.py
- backend/models/meal_plan_models.py
- backend/models/medical_info_model.py
- backend/rag_service.py
- backend/requirements.txt
- backend/routes/chat.py
- backend/routes/login.py
- docker-compose.yml
#174
/ask attributes may include meal_plan_should_be_regenerated and workout_plan_should_be_regenerated which should not be sent back as attributes but as a call to ask for new plan.
/last-meal-plan and /last-workout-plan can be used to fetch last plans.
/history "system" property can be used to check and apply special formatting for plans or hide them from chat.
User "name" is now an attribute.
> Share user info and context about generated plans between models

- backend/rag_service.py
> Experiment on rag similarity threshold

- backend/rag_service.py
- doc_embedding/embed_documents.py
Enforce maximum chunk size using token length, add title and url as chunk metadata, exponential backoff for failed url requests
> Chunking update

- backend/LLMService.py
- backend/database_connection.py
- backend/main.py
- backend/routes/chat.py
- backend/routes/plans.py
- backend/routes/stats.py
- backend/tests/test_chat_history.py
- backend/tests/test_plans.py
- backend/tests/test_stats.py
- backend/user_stats.py
#187
/get-stats can be used to get all stats and progress
Ask responses now include updated "progress" for related stat
"level_up" can be checked to notify user
> User stats

- doc_embedding/embed_documents.py
Removed URLs from RAG documents, completing issue #184.
I didn't do any further cleaning, as there don't seem to be any consistent patterns in the documents that would need to be removed.
> Improve document cleaning by removing URLs

- backend/LLMService.py
- backend/models/chat_model.py
- backend/rag_service.py
- backend/routes/chat.py
- frontend/src/components/Chat.jsx
> Add language support to backend

- backend/LLMService.py
- backend/models/query_rewrite_model.py
- backend/rag_service.py
- Add document retrieval necessity evaluation to query enhancement stage
- Use original user message for final prompting and the enhanced prompt for information retrieval only
> Query enhancement update

- backend/LLMService.py
- backend/database_connection.py
- backend/rag_service.py
> Fix RAG prints

- backend/auth_service.py
- backend/chat_history.py
- backend/database_connection.py
- backend/models/history_request_model.py
- backend/routes/chat.py
- backend/routes/login.py
- backend/routes/user.py
- backend/tests/test_auth_service.py
- backend/tests/test_chat.py
- backend/tests/test_login.py
- backend/tests/test_plans.py
- backend/tests/test_stats.py
- backend/tests/test_user.py
- backend/tests/utils/response.py
- backend/user_stats.py
Added /clear-history to delete chat history and generated plans
Added /unregister to delete account
Added tests for these, improved existing tests and code documentation
> Add endpoint for chat history and account deletion

- backend/LLMService.py
- frontend/src/components/Chat.jsx
Added system instructions and prompting for meal and workout plans
> Add instructions and prompting for meal and workout plans

- frontend/src/components/ChatHistory.jsx
- frontend/src/components/TopBar.jsx
- frontend/src/components/popup/PopupWithTabs.jsx
- frontend/src/components/popup/Profile.jsx
Fixed a bug where user couldn't enter several medical conditions each on its own line
> Fixes in profile, settings and chat history

- backend/rag_service.py
Modified prompting by making user info utilization instructions more elaborate. User info seems to be used a bit better now.
> Improve use of user info in responses

- backend/LLMService.py
Add instructions to the meal and workout plan prompts to improve the explanations. 
The model shouldn't be as eager to needlessly state personal attributes or refer to the user in 3rd person.
> Improve plan prompts for better explanations

- frontend/src/components/ChatHistory.jsx
filters json messages from chat history related to meal and workout plans
> Filter out JSON messages from chat history
